In [1]:
import random as rd

In [10]:
a = rd.randint(1,10)
a

10

In [12]:
score = 80
'good' if score >= 60 else 'bad'
# a if 조건식 else b -> 참일때 a, 거짓일 때 b

'good'

In [13]:
list2 = [1,2,3,['a','b','c']]
print(list2[3])

['a', 'b', 'c']


In [17]:
list_fruit=['사과','배','포도']
list_fruit.append('복숭아')
list_fruit.insert(1,'딸기')
list_fruit

['사과', '딸기', '배', '포도', '복숭아']

ndarray 
수치계산을 위한 핵심 라이브러리
행 열 계산에 최적화 된 패키지를 보유
Nmerical Python 의 줄임말
1. 다양한 수학함수 지원
2. 빠른 연산 속도
3. 브로드 캐스팅
4. 1차원, 2차원, 3차원 등 다양한 차원의 배열 지원

동일한 데이터 타입만 가능

numpy 라이브러리
Numerical Python 약자
수치계산을 위한 핵심 라이브러리
ndarray = N-dimensional array 



In [18]:
import numpy as np

In [19]:
# ndarray 생성하기 : 1차원 리스트 데이터를 array화로 형변환 하는 방법
# list -> array 
list1 = [1,2,3,4]
arr1 = np.array(list1)
arr1

array([1, 2, 3, 4])

In [20]:
type(arr1)

numpy.ndarray

In [21]:
arr2 = np.array([6,7,8,9,10])
arr2

array([ 6,  7,  8,  9, 10])

In [22]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr1.ndim

1

In [24]:
arr1.shape

(4,)

In [25]:
arr1.size

4

In [26]:
len(arr1)

4

In [27]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
arr3.size

6

In [29]:
len(arr3)

2

In [30]:
def array_info(array):
    print(array)
    print('size  : ', array.size)
    print('shape :', array.shape)
    print('ndim : ', array.ndim)

In [31]:
array_info(arr3)

[[1 2 3]
 [4 5 6]]
size  :  6
shape : (2, 3)
ndim :  2


In [37]:
list3 =[[1,2,3],[4,5,6]]
temp1 = np.array(list3)
temp1
array_info(temp1)
temp1.dtype
# 타입 바꾸기
temp2 = np.array(list3, dtype = np.int64)
temp2.dtype

[[1 2 3]
 [4 5 6]]
size  :  6
shape : (2, 3)
ndim :  2


dtype('int64')

In [39]:
temp4 = temp2.astype(np.float64)
temp4.dtype

dtype('float64')

In [43]:
# ndarray 특정 크기 반환
temp5 = temp2.reshape(3,2)
temp5

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int64)

In [44]:
import pandas as pd
import numpy as np

In [45]:
sr = pd.Series([123,456,789])
print(sr)

0    123
1    456
2    789
dtype: int64


In [47]:
sr = pd.Series([123,456,789], index = ['첫', '두','세'])
sr

첫    123
두    456
세    789
dtype: int64

In [48]:
sr.values

array([123, 456, 789], dtype=int64)

In [49]:
sr.array

<PandasArray>
[123, 456, 789]
Length: 3, dtype: int64

In [50]:
sr.index

Index(['첫', '두', '세'], dtype='object')

In [51]:
sr.dtype

dtype('int64')

In [52]:
type(sr)

pandas.core.series.Series

In [54]:
sr.name = '배열'
sr

첫    123
두    456
세    789
Name: 배열, dtype: int64

In [56]:
sr.index.name = '순서'
sr

순서
첫    123
두    456
세    789
Name: 배열, dtype: int64

In [61]:
sr*10


순서
첫    1230
두    4560
세    7890
Name: 배열, dtype: int64

In [62]:
sr[1]

456

In [63]:
sr['첫']

123

In [65]:
sr[ [0,2] ]

순서
첫    123
세    789
Name: 배열, dtype: int64

In [67]:
sr[['첫','세']]

순서
첫    123
세    789
Name: 배열, dtype: int64

In [68]:
sr.iloc[0]

123

In [69]:
sr.iloc[0:1]

순서
첫    123
Name: 배열, dtype: int64

In [70]:
sr.loc['첫']

123

In [72]:
sr.loc['첫':'세']

순서
첫    123
두    456
세    789
Name: 배열, dtype: int64

In [73]:
sr.loc['첫':]

순서
첫    123
두    456
세    789
Name: 배열, dtype: int64

In [75]:
import pandas as pd

In [76]:
df = pd.DataFrame({'name' : ['김','이','박'],
                    '국어' : [90,80,60],
                    '수학' : [50,60,70], })
df

name  국어  수학
0    김  90  50
1    이  80  60
2    박  60  70

In [77]:
df['국어']

0    90
1    80
2    60
Name: 국어, dtype: int64

In [83]:
sum(df['국어'])
# 국어 총점

230

In [84]:
sum(df['국어'])/3

76.66666666666667

In [82]:
# 국어 평균
sum(df['국어'])/len(df)

76.66666666666667

In [80]:
x = [1,2,3,4,5]
len(x)

5

In [1]:
import pandas as pd
import numpy as np

data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12],
    'D': [13, 14, 15, 16]
}

df = pd.DataFrame(data, index=['Row1', 'Row2', 'Row3', 'Row4'])
print(df)

      A  B   C   D
Row1  1  5   9  13
Row2  2  6  10  14
Row3  3  7  11  15
Row4  4  8  12  16


In [6]:
df.loc['Row1':'Row3']

A  B   C   D
Row1  1  5   9  13
Row2  2  6  10  14
Row3  3  7  11  15

In [8]:
df.iloc[0:3]

A  B   C   D
Row1  1  5   9  13
Row2  2  6  10  14
Row3  3  7  11  15

In [9]:
df

A  B   C   D
Row1  1  5   9  13
Row2  2  6  10  14
Row3  3  7  11  15
Row4  4  8  12  16

In [10]:
df.loc[:,'B':'D']

B   C   D
Row1  5   9  13
Row2  6  10  14
Row3  7  11  15
Row4  8  12  16

In [12]:
df.loc['Row2':'Row4', 'B':'D']

B   C   D
Row2  6  10  14
Row3  7  11  15
Row4  8  12  16

In [14]:
df.loc[['Row2','Row4']]

A  B   C   D
Row2  2  6  10  14
Row4  4  8  12  16

In [16]:
df[['A','C']]

A   C
Row1  1   9
Row2  2  10
Row3  3  11
Row4  4  12

In [17]:
df

A  B   C   D
Row1  1  5   9  13
Row2  2  6  10  14
Row3  3  7  11  15
Row4  4  8  12  16

In [1]:
from selenium import webdriver as wb # 웹 브라우저를 제어하기 위한 라이브러리
from selenium.webdriver.common.keys import Keys # 웹에게 값을 '입력'하기 위한 라이버리
from selenium.webdriver.common.by import By # html 문서에서 선택자와 태그의 위치를 찾기위한 라이브러리
from bs4 import BeautifulSoup as bs # 컴퓨터가 이해하기 쉬운 객체로 변환해주는 라이브러리
import time # 코딩 중간에 쉬는시간을 부여해주는 라이브러리
import os # 파일이나 폴더를 생성해주는 라이브러리(파일 시스템 라이브러리)
from urllib.request import urlretrieve # 이미지 경로를 파일로 변환해주는 라이브러리

In [5]:
driver = wb.Chrome()
driver.get('https://www.google.co.kr/?hl=ko')

In [6]:
# 검색창 위치 찾기(By 라이브러리)
search = driver.find_element(By.ID, 'APjFqb')

In [15]:
# 구글에서 네이버 검색해서 네이버메인페이지 들어가는 메소드

driver = wb.Chrome()
driver.get('https://www.google.co.kr/?hl=ko')
# 검색창 위치 찾기(By 라이브러리)
search = driver.find_element(By.ID, 'APjFqb')

# 검색어 입력하기
# search 검색창의 위치
# send_keys('단어') -> '단어'라는 키워드를 검색창에 전송
search.send_keys('네이버')

time.sleep(1)
# 검색버튼 클릭!
btn = driver.find_element(By.NAME, "btnK")
btn.click()

# 네이버 클릭!
btn_naver = driver.find_element(By.CLASS_NAME,'LC20lb.MBeuO.DKV0Md')
btn_naver.click()

In [ ]:
# 구글에서 네이버 검색해서 네이버메인페이지 들어가는 메소드

driver = wb.Chrome()
driver.get('https://www.google.co.kr/?hl=ko')
# 검색창 위치 찾기(By 라이브러리)
search = driver.find_element(By.ID, 'APjFqb')

# 검색어 입력하기
# search 검색창의 위치
# send_keys('단어') -> '단어'라는 키워드를 검색창에 전송
search.send_keys('네이버')

time.sleep(1)
# 검색버튼 클릭!
btn = driver.find_element(By.NAME, "btnK")
btn.click()

# 네이버 클릭!
btn_naver = driver.find_element(By.CLASS_NAME,'LC20lb.MBeuO.DKV0Md')
btn_naver.click()